Add port filter option to allow filtering on either src or dst port
cilium/pwru pull request #141
Opened 2023-01-11 20:34 UTC by msherif1234

adding --filter-port to allow filtering or either source or destination port
which helps on debugging bidirectional TCP/UDP flows.
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

2023-01-12 15:46 UTC, brb requested changes
Thanks! 

1. Shall we make `--filter-{dst,src}-port` mutually exclusive with `--filter-port`?
2. Could you extend the tests to include `--port` ([this](https://github.com/cilium/pwru/blob/main/.github/workflows/test.yml#L88) and [this](https://github.com/cilium/pwru/blob/main/.github/workflows/test.yml#L89))?

2023-01-12 16:55 UTC, msherif1234 commented
@brb I couldn't find out how to run test locally I tried `make release-local` but I don't think that run it ?

2023-01-12 18:35 UTC, msherif1234 commented
@brb is there a way for me to trigger the ci test or u have to trigger it for me ?

2023-01-13 13:09 UTC, brb approved these changes

2023-01-13 13:09 UTC, merged