Changed compiler to clang.
cilium/pwru pull request #282
Opened 2023-10-31 12:10 UTC by devidasjadhav

Closes #221

I have tested this on vm.
Test:
``` bash
sudo mv /usr/bin/gcc{,old}
make clean
make
```

verified binary is executable and running as expected.

Removed LIBPCAP_CC. As it indicates we are using different compilers.
I can revert it if needed.

2023-11-01 13:05 UTC, brb requested changes
Thanks for your PR!

This https://github.com/cilium/pwru/blob/main/local-release.sh needs to be changed too.

2023-11-02 08:34 UTC, brb commented
Thanks. The last bit is to replace gcc with clang for arm64 in `local-release.sh`.

2023-11-02 15:37 UTC, devidasjadhav commented
clang build for arm64 failing when clang replaced by gcc.

```
CC=clang GOARCH=arm64 CGO_ENABLED=1 go build  \
	-ldflags "-w -s \
	-X 'github.com/cilium/pwru/internal/pwru.Version=1e10c19'"
# runtime/cgo
gcc_arm64.S:30:19: error: expected ']' in brackets expression
 stp x29, x30, [sp, #-96]!
                  ^
gcc_arm64.S:34:2: error: unknown use of instruction mnemonic without a size suffix
 mov x29, sp
 ^
gcc_arm64.S:36:19: error: expected ']' in brackets expression
 stp x19, x20, [sp, #80]
                  ^
gcc_arm64.S:39:19: error: expected ']' in brackets expression
 stp x21, x22, [sp, #64]
                  ^
gcc_arm64.S:42:19: error: expected ']' in brackets expression
 stp x23, x24, [sp, #48]
                  ^
gcc_arm64.S:45:19: error: expected ']' in brackets expression
 stp x25, x26, [sp, #32]
                  ^
gcc_arm64.S:48:19: error: expected ']' in brackets expression
 stp x27, x28, [sp, #16]
                  ^
gcc_arm64.S:52:2: error: unknown use of instruction mnemonic without a size suffix
 mov x19, x0
 ^
gcc_arm64.S:53:2: error: unknown use of instruction mnemonic without a size suffix
 mov x20, x1
 ^
gcc_arm64.S:54:2: error: unknown use of instruction mnemonic without a size suffix
 mov x0, x2
 ^
gcc_arm64.S:56:2: error: invalid instruction mnemonic 'blr'
 blr x20
 ^~~
gcc_arm64.S:57:2: error: invalid instruction mnemonic 'blr'
 blr x19
 ^~~
gcc_arm64.S:59:19: error: expected ']' in brackets expression
 ldp x27, x28, [sp, #16]
                  ^
gcc_arm64.S:62:19: error: expected ']' in brackets expression
 ldp x25, x26, [sp, #32]
                  ^
gcc_arm64.S:65:19: error: expected ']' in brackets expression
 ldp x23, x24, [sp, #48]
                  ^
gcc_arm64.S:68:19: error: expected ']' in brackets expression
 ldp x21, x22, [sp, #64]
                  ^
gcc_arm64.S:71:19: error: expected ']' in brackets expression
 ldp x19, x20, [sp, #80]
                  ^
gcc_arm64.S:74:22: error: unknown token in expression
 ldp x29, x30, [sp], #96
                     ^
make: *** [Makefile:21: pwru] Error 1
```

I had only changed gcc to clan in arm64.

2023-11-02 15:50 UTC, brb commented
https://stackoverflow.com/questions/51475992/cgo-cross-compiling-from-amd64linux-to-arm64linux might help.

2023-11-03 07:01 UTC, devidasjadhav commented
Found root cause of issue.

- clang is not cross compiler. 
- when clang compiled libpcap it generated object files for x86_64. 
-  which in turn caused compile error

also found similar issue. 
https://github.com/golang/go/issues/28966#issuecomment-547558462

trying to figure out clang compiler and compiling using aarch64 clang binary.
https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.4/clang+llvm-17.0.4-aarch64-linux-gnu.tar.xz

as well as I will check if there is any repo hosting these clang.

@brb any pointers about this ?

2023-11-03 07:04 UTC, devidasjadhav commented
just realized 
https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.4/clang+llvm-17.0.4-aarch64-linux-gnu.tar.xz 

is not cross-compiler rather its clang for aarch64.

2023-11-03 08:24 UTC, brb commented
Could we use a clang cross-compiler for arm64? https://clang.llvm.org/docs/CrossCompilation.html

2023-11-03 12:16 UTC, devidasjadhav commented
I am able to cross compile libpcap.
Now only issue is cgo compilation.
Which is 
exact same go files are building fine with cc=aarch64-unknown-linux-gnu
But fails when cc=clang

@brb any pointers ?
PS: I have used workaround for cross compilation as of now.

2023-11-03 13:04 UTC, brb commented
> building fine with cc=aarch64-unknown-linux-gnu

Is it GCC or Clang?

2023-11-07 07:13 UTC, brb commented
In order to cross compile with Clang, you need to set `--target`. Try setting it via `CFLAGS="--target=aarch64-unknown-linux"` when compiling with Cgo.

2023-11-07 13:16 UTC, devidasjadhav commented
Yes Now I can compile.
Linker error. as it is using linker '/usr/local/go/pkg/tool/linux_386/link'
CC=clang CGO_CFLAGS="--target=aarch64-unknown-linux" GOARCH=arm64 CGO_ENABLED=1 go build  \
        -ldflags "-w -s \
        -X 'github.com/cilium/pwru/internal/pwru.Version=2f22f3f'"
# github.com/cilium/pwru
/usr/local/go/pkg/tool/linux_386/link: running clang failed: exit status 1
/usr/bin/ld: /tmp/go-link-1420334561/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-1420334561/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-1420334561/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-1420334561/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-1420334561/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-1420334561/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-1420334561/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-1420334561/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-1420334561/go.o: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/go-link-1420334561/go.o: error adding symbols: file in wrong format
clang: error: linker command failed with exit code 1 (use -v to see invocation)

2023-11-07 14:01 UTC, devidasjadhav commented
here is execsnoop output.

```
$ sudo /usr/share/bcc/tools/execsnoop
PCOMM            PID     PPID    RET ARGS
go               38007   1266      0 /usr/local/go/bin/go build -ldflags -w -s         -X 'github.com/cilium/pwru/internal
/pwru.Version=2f22f3f'
clang            38081   38080     0 /usr/lib/llvm-14/bin/clang -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --m
relax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name triv
ial.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno
ld               38082   38080     0 /usr/bin/ld -pie --hash-style=both --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-l
inker /lib64/ld-linux-x86-64.so.2 -o /tmp/go-link-2893705073/a.out /lib/x86_64-linux-gnu/Scrt1.o /lib/x86_64-linux-gnu/crt
i.o /usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtbeginS.o -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12 -L/usr/bin/../lib/gcc/x8
6_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib6
4
```

Which means target flag is not used by go build i.e. cgo is not compiling for arm64.

2023-11-08 10:08 UTC, brb commented
Maybe try this hack `CC="clang --target=aarch64-unknown-linux" ...`.

2023-12-20 07:48 UTC, brb commented
@devidasjadhav :wave: any update on this PR?

2024-03-01 10:15 UTC, brb commented
@devidasjadhav I'm closing this PR due to inactivity. Please let me know if I need to reopen.

2024-03-01 10:15 UTC, closed without merging