internal/pwru: Match entire string for --filter-func
cilium/pwru pull request #44
Opened 2021-12-22 22:35 UTC by ypl-coffee

Hi all,

Currently `--filter-func=kfree_skb` matches all functions whose name
contains the `"kfree_skb"` string, including `__kfree_skb()`, `kfree_skbmem()`
etc.  To match `kfree_skb()` only, one has to do something like
`--filter-func="^kfree_skb$"`.

This is counterintuitive.  Match the entire string instead in
`GetFuncs()`, so that `--filter-func=kfree_skb` only matches `kfree_skb()`.
To match all function names containing `"kfree_skb"`, one should do
something like `--filter-func=".*kfree_skb.*"` instead.

Thanks,
Signed-off-by: Peilin Ye <peilin.ye@bytedance.com>

2022-01-20 11:00 UTC, brb requested changes
Hey, thanks for the PR and sorry for the delay.

I'm fine with the change. Could you update the flag description and README.md to mention the exact match and how wildcarded match can be set?

2022-01-20 11:12 UTC, gandro commented on internal/pwru/utils.go
> +		if pattern != "" && reg.FindString(fnName) != fnName {
`FindString` does a prefix match. Is that intended? With that code, `--filter-func=kfree_sbk would still match kfree_skbmem` https://go.dev/play/p/M3yIKZpCVf8

2022-01-20 23:46 UTC, ypl-coffee commented
> Hey, thanks for the PR and sorry for the delay.

Thanks for the review.

> I'm fine with the change. Could you update the flag description and README.md to mention the exact match and how wildcarded match can be set?

Sure of course, I just did a force-push.

2022-01-21 08:28 UTC, brb approved these changes
Thanks!

2022-01-21 08:31 UTC, merged