Enable kprobe-multi for kmods by default
cilium/pwru pull request #470
Opened 2024-12-17 13:30 UTC by rgo3

This commit enables using the kprobe-multi backend for tracing functions in kernel modules by default if supported. Previously that was only possible by specifying the `--backend=kprobe-multi` option.

Fixes #147

2024-12-17 13:35 UTC, rgo3 commented
Observation:
Running with kprobe backend:
```
sudo ./pwru --backend kprobe --kmods wireguard --filter-mark 0x0e00
2024/12/17 14:11:07 Attaching kprobes (via kprobe)...
1572 / 1572 [-----------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 184 p/s
2024/12/17 14:11:16 Attached (ignored 115)
2024/12/17 14:11:16 Listening for `events..`
```

Running with kprobe-multi backend:
```
sudo ./pwru --kmods wireguard --filter-mark 0x0e00
2024/12/17 14:32:28 Attaching kprobes (via kprobe-multi)...
1480 / 1460 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------] 101.37% ? p/s
2024/12/17 14:32:28 Attached (ignored 20)
2024/12/17 14:32:28 Listening for events..
```
@brb Do the respective numbers we observe for attached and ignored functions make sense? I'm having a hard time coming up with a meaningful way to test if enabling the kprobe-multi backend breaks any attachments.

2024-12-19 07:27 UTC, jschwinger233 reviewed
I think we can compare what's been ignored by kprobe to kprobemulti. For example, we can `print(fn)` at https://github.com/cilium/pwru/blob/v1.0.10-pre/internal/pwru/kprobe.go#L180.

My feeling is this is fine, since kprobemulti ignored less targets (20) than kprobe (115).

2024-12-19 07:27 UTC, jschwinger233 approved these changes

2024-12-19 15:49 UTC, brb requested changes
Thanks for the PR!

Unfortunately, I don't see kmods in a pwru traces.

The way I tested.
1. Block 1.1.1.1 with `iptables -t filter -I OUTPUT 1 -m tcp --proto tcp --dst 1.1.1.1/32 -j DROP`.
2. Run pwru with your changes:
```
KMODS=$(ls /sys/kernel/btf/ | grep -v vmlinux | grep -E '(ip|xt|nf)' | tr '\n' , | sed 's/.$//')
./pwru --kmods="$KMODS" 'host 1.1.1.1 and port 80'
```
3. Observe that `curl 1.1.1.1` does not show any function calls from netfilter modules.
4. Run `./pwru --kmods="$KMODS" --backend=kprobe 'host 1.1.1.1 and port 80'` and see the modules, e.g.:
```
59:36298->1.1.1.1:80(tcp) nf_nat_ipv4_local_fn[nf_nat]
0xffff9feec55880e8 4   <empty>:0        4026531840 0               0         0x0800 1500  60    192.168.1.159:36298->1.1.1.1:80(tcp) sk_skb_reason_drop(SKB_DROP_REASON_NETFILTER_DROP)
```

My gut feeling is that the kmod functions are being ignored due to not exposed in the `available_filter_functions` (see https://github.com/cilium/pwru/issues/147#issuecomment-2536152499).

2024-12-20 08:50 UTC, rgo3 commented
Yes agreed, it definitely needs some troubleshooting. Thanks for the test example, I'll start by taking a look at which funcs get ignored for the respective backend. However, on my machine the `available_filter_functions` file does contain funcs of kmods so this might not be the issue we are seeing. In any case, will turn the PR to a draft and reopen once I've figured out more.

2024-12-24 14:43 UTC, rgo3 commented
I think I fixed it, had to make sure we parse out functions from kmods in `available_filter_functions` and `kallsyms` files the same way. Merry Christmas everyone :christmas_tree:

2024-12-27 10:14 UTC, brb approved these changes
Nice, thank you! Happy X-mas :pizza:

2024-12-27 10:30 UTC, merged